stages:
  - test
  - deploy

include:
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml

line count:
  stage: test
  needs: []
  image:
    name: ghcr.io/boyter/scc:master
    entrypoint: [""]
  script:
    - mkdir -p line_count
    - scc
      --format-multi "tabular:stdout,html:line_count/line_count.html"
      --count-as "h:C++,hpp:C++"
      .
    - scc
      --format-multi "tabular:stdout,html:line_count/src_line_count.html"
      --count-as "h:C++,hpp:C++"
      --by-file -s complexity
      cpp/include cpp/src src
  artifacts:
    paths:
      - line_count
  interruptible: true

spell check:
  stage: test
  needs: []
  image: node
  script:
    - npm install -g cspell
    - cspell lint
      "**/*.h"
      "**/*.cpp"
      "**/*.py"
      "**/*.cmake"
      "**/*.txt"
      "**/*.md"
      "**/*.rst"
      "**/*.puml"
      "**/*.bib"
      "**/*.yaml"
      "**/*.yml"
      "**/*.json"
      "**/*.toml"
      "**/*.sh"
      "**/*.bash"
      --exclude "**/*.approved.*"
      --exclude "vcpkg/*"
  interruptible: true

.test linux base:
  stage: test
  needs: []
  parallel:
    matrix:
      - COMPILER_TYPE: ["clang22"]
        IMAGE_PATH: "musicscience37/clang-ci"
        TEST_TYPE: "release"
  image: ${IMAGE_PATH}:${COMPILER_TYPE}
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    BUILD_DIR: build_${COMPILER_TYPE}_${TEST_TYPE}
    CCACHE_DIR: ${CI_PROJECT_DIR}/.ccache
    CCACHE_COMPILERCHECK: content
    CCACHE_MAXSIZE: 1G
    VCPKG_DEFAULT_BINARY_CACHE: ${CI_PROJECT_DIR}/.vcpkg-cache
    POETRY_CACHE_DIR: ${CI_PROJECT_DIR}/.poetry-cache
  before_script:
    - poetry config virtualenvs.in-project true
    - poetry env use 3.13
    - poetry install
    - mkdir -p $VCPKG_DEFAULT_BINARY_CACHE
    - mkdir $BUILD_DIR
    - apt-get update
    - apt-get install -y libmtdev1 xvfb
  script:
    - poetry run python ./scripts/ci_linux_test.py
      --compiler_type $COMPILER_TYPE --test_type $TEST_TYPE --build_dir $BUILD_DIR
  cache:
    - key:
        prefix: poetry-${COMPILER_TYPE}-${TEST_TYPE}
        files:
          - poetry.lock
      paths:
        - .poetry-cache
    - key:
        prefix: vcpkg-${COMPILER_TYPE}-${TEST_TYPE}
        files:
          - vcpkg-configuration.json
      paths:
        - .vcpkg-cache
    - key: ccache-${COMPILER_TYPE}-${TEST_TYPE}
      paths:
        - .ccache
  artifacts:
    paths:
      - $BUILD_DIR/junit
      - $BUILD_DIR/temp_test
    reports:
      junit:
        - $BUILD_DIR/junit/*.xml
    when: always
  interruptible: true

test linux:
  extends: .test linux base
  parallel:
    matrix:
      - COMPILER_TYPE: ["clang22"]
        IMAGE_PATH: "musicscience37/clang-ci"
        TEST_TYPE: ["debug", "release", "ausan"]
  script:
    - poetry run python ./scripts/ci_linux_test.py
      --compiler_type $COMPILER_TYPE --test_type $TEST_TYPE --build_dir $BUILD_DIR

cpp coverage:
  extends: .test linux base
  parallel:
    matrix:
      - COMPILER_TYPE: ["clang22"]
        IMAGE_PATH: "musicscience37/clang-ci"
        TEST_TYPE: ["coverage_cpp"]
  script:
    - poetry run python ./scripts/ci_linux_test.py
      --compiler_type $COMPILER_TYPE --test_type $TEST_TYPE --build_dir $BUILD_DIR
    - ./scripts/collect_llvm_coverage.sh $BUILD_DIR
    - poetry run lcov_cobertura $BUILD_DIR/coverage/coverage --output $BUILD_DIR/coverage/coverage.xml
  coverage: '/[^\s]+%\s+\d+\s+\d+\s+\s[^\s]+%/'
  artifacts:
    paths:
      - $BUILD_DIR/junit
      - $BUILD_DIR/temp_test
      - $BUILD_DIR/coverage
    reports:
      junit:
        - $BUILD_DIR/junit/*.xml
      coverage_report:
        coverage_format: cobertura
        path: $BUILD_DIR/coverage/coverage.xml
    when: always

python coverage:
  extends: .test linux base
  parallel:
    matrix:
      - COMPILER_TYPE: ["clang22"]
        IMAGE_PATH: "musicscience37/clang-ci"
        TEST_TYPE: ["coverage_python"]
  script:
    - poetry run python ./scripts/ci_linux_test.py
      --compiler_type $COMPILER_TYPE --test_type $TEST_TYPE --build_dir $BUILD_DIR
  coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    paths:
      - $BUILD_DIR/junit
      - $BUILD_DIR/temp_test
      - coverage_python.xml
      - coverage_python
    reports:
      junit:
        - $BUILD_DIR/junit/*.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage_python.xml

pre-commit:
  extends: .test linux base
  parallel:
    matrix:
      - COMPILER_TYPE: ["clang22"]
        IMAGE_PATH: "musicscience37/clang-ci"
        TEST_TYPE: "pre-commit"
  script:
    - poetry run python ./scripts/ci_linux_test.py
      --compiler_type $COMPILER_TYPE --test_type $TEST_TYPE --build_dir $BUILD_DIR

docs:
  extends: .test linux base
  parallel:
    matrix:
      - COMPILER_TYPE: ["clang22"]
        IMAGE_PATH: "musicscience37/sphinx-doxygen"
        TEST_TYPE: "docs"
  script:
    - poetry run python ./scripts/ci_linux_test.py
      --compiler_type $COMPILER_TYPE --test_type $TEST_TYPE --build_dir $BUILD_DIR
  artifacts:
    paths:
      - docs/build/html

pages main:
  stage: deploy
  needs:
    - "docs: [clang22, musicscience37/sphinx-doxygen, docs]"
    - "cpp coverage: [clang22, musicscience37/clang-ci, coverage_cpp]"
    - "python coverage: [clang22, musicscience37/clang-ci, coverage_python]"
  dependencies:
    - "docs: [clang22, musicscience37/sphinx-doxygen, docs]"
    - "cpp coverage: [clang22, musicscience37/clang-ci, coverage_cpp]"
    - "python coverage: [clang22, musicscience37/clang-ci, coverage_python]"
  image: alpine
  script:
    - mv docs/build/html public
    - mv build_clang22_coverage_cpp/coverage/html public/coverage_cpp
    - mv coverage_python public/coverage_python
  artifacts:
    paths:
      - public
  pages: true
