stages:
  - test

include:
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml

line count:
  stage: test
  needs: []
  image: registry.gitlab.com/musicscience37projects/docker/scc-docker
  script:
    - mkdir -p line_count
    - scc
      --format-multi "tabular:stdout,html:line_count/line_count.html"
      -i h,cpp
      .
  artifacts:
    paths:
      - line_count
    expire_in: "1 mos"
  interruptible: true

pre-commit:
  stage: test
  needs: []
  image: musicscience37/clang-ci:clang22
  variables:
    POETRY_CACHE_DIR: ${CI_PROJECT_DIR}/.poetry-cache
  script:
    - poetry config virtualenvs.in-project true
    - poetry env use 3.13
    - poetry sync
    - poetry run pre-commit run --all-files
  cache:
    - key:
        prefix: poetry-linux
        files:
          - poetry.lock
      paths:
        - .poetry-cache
  interruptible: true

spell check:
  stage: test
  needs: []
  image: node
  script:
    - npm install -g cspell
    - cspell lint
      "**/*.h"
      "**/*.cpp"
      "**/*.py"
      "**/*.cmake"
      "**/*.txt"
      "**/*.md"
      "**/*.rst"
      "**/*.puml"
      "**/*.bib"
      "**/*.yaml"
      "**/*.yml"
      "**/*.json"
      "**/*.toml"
      "**/*.sh"
      "**/*.bash"
      --exclude "**/*.approved.*"
      --exclude "vcpkg/*"
  interruptible: true

doc:
  stage: test
  needs: []
  image: musicscience37/sphinx-doxygen:clang22
  variables:
    POETRY_CACHE_DIR: ${CI_PROJECT_DIR}/.poetry-cache
  script:
    - poetry config virtualenvs.in-project true
    - poetry env use 3.13
    - poetry sync
    - poetry run ./docs/build.sh
  artifacts:
    paths:
      - docs/build/html
    expire_in: "1 mos"
  cache:
    - key:
        prefix: poetry-linux
        files:
          - poetry.lock
      paths:
        - .poetry-cache
  interruptible: true
