sonar.projectKey=MusicScience37Projects_func-sketch
sonar.organization=musicscience37projects

sonar.projectName=FuncSketch

sonar.sources=cpp/include,cpp/src,src
sonar.tests=cpp/tests,tests,bench

sonar.sourceEncoding=UTF-8

sonar.python.version=3.13
