@startuml classes_cpp

package func_sketch {
    class Scalar <<typedef>> {
        using Scalar = double
    }

    class Vector <<typedef>> {
        using Vector = Eigen::VectorXd
    }

    class ArgumentVariant <<typedef>> {
        using ArgumentVariant = std::variant<Scalar, Vector>
    }

    enum ParameterType {
        X
    }

    package utilities {
        class Any {
            + Any(object : T)
            + get<T>() : const T&
        }
    }

    package math {
        class UnaryOperator {
            + operator()(arg : Scalar, result : Scalar&)
            + operator()(arg : ArgumentVariant, result : ArgumentVariant&)
        }
        UnaryOperator o-- Any

        class BinaryOperator {
            + operator()(left : Scalar, right : Scalar, result : Scalar&)
            + operator()(left : ArgumentVariant, right : ArgumentVariant, result : ArgumentVariant&)
        }
        BinaryOperator o-- Any

        class MathFunction {
            + operator()(args : std::vector<Scalar>, result : Scalar&)
            + operator()(args : std::vector<ArgumentVariant>, result : ArgumentVariant&)
        }
        MathFunction o-- Any

        class MathFunctionList {
            + emplace(function : MathFunction)
            + get(name : std::string) : std::optional<MathFunction>
        }
        MathFunctionList o-- MathFunction

        note as math_functions_note
            Actual mathematical functions and operators
            are implemented here too.
        end note
    }

    package expressions {
        class Expression {
            - expression_ : std::variant<ConstantExpression, ParameterExpression, UnaryExpression, BinaryExpression, FunctionCallExpression>
        }

        struct ConstantExpression {
            + value : Scalar
        }
        Expression <..> ConstantExpression

        struct ParameterExpression {
            + type : ParameterType
        }
        Expression <..> ParameterExpression
        ParameterExpression o-- ParameterType

        struct UnaryExpression {
            + target : Expression*
            + operator_object : UnaryOperator
        }
        Expression <..> UnaryExpression
        UnaryExpression o-- UnaryOperator

        struct BinaryExpression {
            + left : Expression*
            + right : Expression*
            + operator_object : BinaryOperator
        }
        Expression <..> BinaryExpression
        BinaryExpression o-- BinaryOperator

        struct FunctionCallExpression {
            + arguments : std::vector<Expression*>
            + function : MathFunction
        }
        Expression <..> FunctionCallExpression
        FunctionCallExpression o-- MathFunction

        class ExpressionMemoryPool {
            + create<T>(args...) : Expression*
        }
        ExpressionMemoryPool ..> Expression

        class ExpressionEvaluator {
            + operator()(expression : const Expression&, parameter : Scalar, result : Scalar&)
            + operator()(expression : const Expression&, parameter : ArgumentVariant, result : ArgumentVariant&)
        }

        class ExpressionPtr
        ExpressionPtr o-- Expression
        ExpressionPtr o-- ExpressionMemoryPool
    }

    package parser {
        class ExpressionParser {
            + operator()(expression_str : std::string) : ExpressionPtr
        }
        ExpressionParser o-- MathFunctionList
        ExpressionParser ..> ExpressionPtr
    }

    package plotter {
        struct RGBColor {
            + r : uint8_t
            + g : uint8_t
            + b : uint8_t
        }

        struct Point {
            + x : Scalar
            + y : Scalar
        }

        class Image <<typedef>> {
            using Image = cv::Mat
        }

        class PlotRange {
            + x_range() : std::pair<Scalar, Scalar>
            + y_range() : std::pair<Scalar, Scalar>
        }

        struct PlotConfig

        class FunctionSampler {
            + range(value : PlotRange)
            + config(value : PlotConfig)
            + operator()(function : ExpressionPtr) : std::vector<Point>
        }
        FunctionSampler o-- PlotRange
        FunctionSampler o-- PlotConfig
        FunctionSampler ...> ExpressionPtr
        FunctionSampler ..> Point

        class Plotter {
            + range(value : PlotRange)
            + config(value : PlotConfig)
            + write_background(image : Image&)
            + write_curve(samples : std::vector<Point>, color : RGBColor, image : Image&)
        }
        Plotter o-- PlotRange
        Plotter o-- PlotConfig
        Plotter ..> Point
        Plotter ..> RGBColor
        Plotter ..> Image
    }
}

@enduml
