@startuml classes_cpp

package func_sketch {
    class Real <<typedef>> {
        using Real = double
    }

    class Complex <<typedef>> <<future-implementation>> {
        using Complex = std::complex<double>
    }

    class Integer <<typedef>> {
        using Integer = int32_t
    }

    class Number <<typedef>> {
        using Number = std::variant<Integer, Real, Complex>
    }

    class RealVector <<typedef>> <<future-implementation>> {
        using RealVector = Eigen::VectorXd
    }

    class ComplexVector <<typedef>> <<future-implementation>> {
        using ComplexVector = Eigen::VectorXcd
    }

    class VectorizedNumber <<typedef>> <<future-implementation>> {
        using VectorizedNumber = std::variant<Integer, Real, Complex, RealVector, ComplexVector>
    }

    enum ParameterType <<future-implementation>> {
        x
        t
    }

    package utilities {
        class Any {
            + Any(object : T)
            + get<T>() : const T&
        }
    }

    package math {
        class UnaryOperator {
            + operator()(arg : Number, result : Number&)
            + operator()(arg : VectorizedNumber, result : VectorizedNumber&)
        }
        UnaryOperator o-- Any

        class BinaryOperator {
            + operator()(left : Number, right : Number, result : Number&)
            + operator()(left : VectorizedNumber, right : VectorizedNumber, result : VectorizedNumber&)
        }
        BinaryOperator o-- Any

        class MathFunction {
            + operator()(args : std::vector<Number>, result : Number&)
            + operator()(args : std::vector<VectorizedNumber>, result : VectorizedNumber&)
        }
        MathFunction o-- Any

        class MathFunctionList {
            + emplace(function : MathFunction)
            + get(name : std::string) : std::optional<MathFunction>
        }
        MathFunctionList o-- MathFunction

        note as math_functions_note
            Actual mathematical functions and operators
            are implemented here too.
        end note
    }

    package expressions {
        class Expression {
            - expression_ : std::variant<ConstantExpression, ParameterExpression, UnaryExpression, BinaryExpression, FunctionCallExpression>
        }

        struct ConstantExpression {
            + value : Number
        }
        Expression <..> ConstantExpression

        struct ParameterExpression {
            + type : ParameterType
        }
        Expression <..> ParameterExpression
        ParameterExpression o-- ParameterType

        struct UnaryExpression {
            + target : Expression*
            + operator_object : UnaryOperator
        }
        Expression <..> UnaryExpression
        UnaryExpression o-- UnaryOperator

        struct BinaryExpression {
            + left : Expression*
            + right : Expression*
            + operator_object : BinaryOperator
        }
        Expression <..> BinaryExpression
        BinaryExpression o-- BinaryOperator

        struct FunctionCallExpression {
            + arguments : std::vector<Expression*>
            + function : MathFunction
        }
        Expression <..> FunctionCallExpression
        FunctionCallExpression o-- MathFunction

        class ExpressionMemoryPool {
            + create<T>(args...) : Expression*
        }
        ExpressionMemoryPool ..> Expression

        class ExpressionEvaluator {
            + operator()(expression : const Expression&, parameter : Real, result : Real&)
            + operator()(expression : const Expression&, parameter : RealVector, result : RealVector&)
        }

        class ExpressionPtr
        ExpressionPtr o-- Expression
        ExpressionPtr o-- ExpressionMemoryPool
    }

    package parser {
        class ExpressionParser {
            + operator()(expression_str : std::string) : ExpressionPtr
        }
        ExpressionParser o-- MathFunctionList
        ExpressionParser ..> ExpressionPtr
    }

    package plotter {
        struct RGBColor {
            + r : uint8_t
            + g : uint8_t
            + b : uint8_t
        }

        struct Point {
            + x : Real
            + y : Real
        }

        class Image <<typedef>> {
            using Image = cv::Mat
        }

        class PlotRange {
            + x_range() : std::pair<Real, Real>
            + y_range() : std::pair<Real, Real>
        }

        struct PlotConfig

        class FunctionSampler {
            + range(value : PlotRange)
            + config(value : PlotConfig)
            + operator()(function : ExpressionPtr) : std::vector<Point>
        }
        FunctionSampler o-- PlotRange
        FunctionSampler o-- PlotConfig
        FunctionSampler ...> ExpressionPtr
        FunctionSampler ..> Point

        class Plotter {
            + range(value : PlotRange)
            + config(value : PlotConfig)
            + write_background(image : Image&)
            + write_curve(samples : std::vector<Point>, color : RGBColor, image : Image&)
        }
        Plotter o-- PlotRange
        Plotter o-- PlotConfig
        Plotter ..> Point
        Plotter ..> RGBColor
        Plotter ..> Image
    }
}

@enduml
