@startuml structure_module

package "FuncSketch" {
    package "Python Module" {
        component "GUI"
    }

    package "C++ Module" {
        component "Expression Parser"
        component "Function Calculator"
        component "Function Plotter"
    }
}

package "Third Party Libraries" {
    package "Python Libraries" {
        component "Kivy"
    }

    package "C++ Libraries" {
        component "Boost.Spirit"
        component "Boost.Math"
        component "Eigen"
        component "OpenCV"
        component "nanobind"
        component "fmt"
    }
}

"GUI" ..> "Expression Parser"
"GUI" ..> "Function Calculator"
"GUI" ..> "Function Plotter"
"Expression Parser" .> "Function Calculator"
"Function Plotter" .> "Function Calculator"

"GUI" ..> "Kivy"
"Expression Parser" ..> "Boost.Spirit"
"Function Calculator" ..> "Eigen"
"Function Calculator" ..> "Boost.Math"
"Function Plotter" ..> "Eigen"
"Function Plotter" ..> "OpenCV"
"C++ Module" ..> "nanobind"
"C++ Module" ..> "fmt"

note as boost_spirit_note
    For parsing
    mathematical
    expressions.
end note
"Boost.Spirit" .. boost_spirit_note

note as boost_math_note
    For special functions
    not in Eigen.
end note
"Boost.Math" .. boost_math_note

note as eigen_note
    For vector
    operations.
end note
"Eigen" .. eigen_note

note as opencv_note
    For plotting.
end note
"OpenCV" .. opencv_note

note as nanobind_note
    For binding
    C++ code
    to Python.
end note
"nanobind" .. nanobind_note

note as fmt_note
    For formatting
    strings.
end note
"fmt" .. fmt_note

note as kivy_note
    For GUI
    development.
end note
"Kivy" .. kivy_note

@enduml
