# Copyright 2026 MusicScience37 (Kenta Kabashima)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#:import FONT_SIZE_HEADER1 func_sketch._gui.common.constants.FONT_SIZE_HEADER1
#:import FONT_SIZE_TEXT func_sketch._gui.common.constants.FONT_SIZE_TEXT
#:import SPACING_HEADER2 func_sketch._gui.common.constants.SPACING_HEADER2
#:import SPACING_DEFAULT func_sketch._gui.common.constants.SPACING_DEFAULT

#:import SwitchWidget func_sketch._gui.common.switch_widget.SwitchWidget

<CurveSpecListWidget>:
    orientation: "vertical"
    size_hint_y: None
    height: self.minimum_height
    spacing: SPACING_HEADER2
    GridLayout:
        cols: 2
        size_hint_y: None
        height: self.minimum_height
        spacing: SPACING_DEFAULT
        Label:
            text: "Show legend:"
            font_size: FONT_SIZE_TEXT
            text_size: self.width, None
            halign: "left"
        SwitchWidget:
            id: show_legend_switch
            size_hint_y: None
            height: self.texture_size[1]
            active: False
    BoxLayout:
        id: curve_spec_list_layout
        orientation: "vertical"
        size_hint_y: None
        height: self.minimum_height
        spacing: SPACING_HEADER2
