# Copyright 2026 MusicScience37 (Kenta Kabashima)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#:import FloatTextInput func_sketch._gui.common.float_text_input.FloatTextInput
#:import FONT_SIZE_HEADER1 func_sketch._gui.common.constants.FONT_SIZE_HEADER1
#:import FONT_SIZE_HEADER2 func_sketch._gui.common.constants.FONT_SIZE_HEADER2
#:import FONT_SIZE_TEXT func_sketch._gui.common.constants.FONT_SIZE_TEXT
#:import FONT_SIZE_STATUS_BAR func_sketch._gui.common.constants.FONT_SIZE_STATUS_BAR
#:import SPACING_DEFAULT func_sketch._gui.common.constants.SPACING_DEFAULT
#:import SPACING_HEADER1 func_sketch._gui.common.constants.SPACING_HEADER1
#:import SPACING_HEADER2 func_sketch._gui.common.constants.SPACING_HEADER2
#:import PADDING_NAVIGATION func_sketch._gui.common.constants.PADDING_NAVIGATION
#:import PADDING_STATUS_BAR func_sketch._gui.common.constants.PADDING_STATUS_BAR
#:import NORMAL_TEXT_COLOR func_sketch._gui.common.constants.NORMAL_TEXT_COLOR
#:import SPLITTER_COLOR func_sketch._gui.common.constants.SPLITTER_COLOR
#:import NAVIGATION_BACKGROUND_COLOR func_sketch._gui.common.constants.NAVIGATION_BACKGROUND_COLOR
#:import STATUS_BAR_BACKGROUND_COLOR func_sketch._gui.common.constants.STATUS_BAR_BACKGROUND_COLOR
#:import SECTION_BORDER_COLOR func_sketch._gui.common.constants.SECTION_BORDER_COLOR

#:include common/common.kv
#:include plot_2d/range_config_widget.kv
#:include plot_2d/curve_spec_widget.kv
#:include plot_2d/curve_spec_list_widget.kv
#:include plot_2d/image_size_widget.kv
#:import CurveSpecListWidget func_sketch._gui.plot_2d.curve_spec_list_widget.CurveSpecListWidget
#:import PlainSplitterStrip func_sketch._gui.common.plain_splitter_strip.PlainSplitterStrip
#:import PlotWidget func_sketch._gui.plot_2d.plot_widget.PlotWidget
#:import RangeConfigWidget func_sketch._gui.plot_2d.range_config_widget.RangeConfigWidget
#:import StatusBarWidget func_sketch._gui.plot_2d.status_bar_widget.StatusBarWidget
#:import CollapsibleBox func_sketch._gui.common.collapsible_box.CollapsibleBox
#:import MenuWidget func_sketch._gui.plot_2d.menu_widget.MenuWidget
#:import ImageSizeWidget func_sketch._gui.plot_2d.image_size_widget.ImageSizeWidget

<Splitter>:
    strip_cls: PlainSplitterStrip

<FuncSketchWidget>
    orientation: "vertical"
    MenuWidget:
        shared_state: root.shared_state
    BoxLayout:
        orientation: "horizontal"
        PlotWidget:
            shared_state: root.shared_state
        Splitter:
            canvas.before:
                Color:
                    rgba: NAVIGATION_BACKGROUND_COLOR
                Rectangle:
                    pos: self.pos
                    size: self.size
            sizable_from: "left"
            size_hint_x: None
            width: 300
            minimum_width: 200
            max_width: 1000
            strip_size: 10
            ScrollView:
                BoxLayout:
                    orientation: "vertical"
                    size_hint_y: None
                    height: self.minimum_height
                    # No spacing here. Padding is sufficient for the spacing.
                    CollapsibleBox:
                        title: "Curves"
                        padding: PADDING_NAVIGATION
                        canvas:
                            Color:
                                rgba: SECTION_BORDER_COLOR
                            Line:
                                points: [self.x, self.y, self.x + self.width, self.y]
                        CurveSpecListWidget:
                            shared_state: root.shared_state
                    CollapsibleBox:
                        title: "Range"
                        padding: PADDING_NAVIGATION
                        canvas:
                            Color:
                                rgba: SECTION_BORDER_COLOR
                            Line:
                                points: [self.x, self.y, self.x + self.width, self.y]
                        RangeConfigWidget:
                            shared_state: root.shared_state
                    CollapsibleBox:
                        title: "Image Size"
                        padding: PADDING_NAVIGATION
                        ImageSizeWidget:
                            shared_state: root.shared_state
    StatusBarWidget:
        canvas.before:
            Color:
                rgba: STATUS_BAR_BACKGROUND_COLOR
            Rectangle:
                pos: self.pos
                size: self.size
        shared_state: root.shared_state
        size_hint_y: None
        height: FONT_SIZE_STATUS_BAR + 2 * PADDING_STATUS_BAR
        text_size: self.width, None
        font_size: FONT_SIZE_STATUS_BAR
        padding: PADDING_STATUS_BAR
