# Copyright 2026 MusicScience37 (Kenta Kabashima)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#:import FONT_SIZE_TEXT func_sketch._gui.common.constants.FONT_SIZE_TEXT
#:import SPACING_DEFAULT func_sketch._gui.common.constants.SPACING_DEFAULT

#:import SwitchWidget func_sketch._gui.common.switch_widget.SwitchWidget
#:import PlainTextInput func_sketch._gui.common.plain_text_input.PlainTextInput

<ImageSizeWidget>:
    orientation: "vertical"
    size_hint_y: None
    height: self.minimum_height
    spacing: SPACING_DEFAULT
    GridLayout:
        cols: 2
        size_hint_y: None
        height: self.minimum_height
        spacing: SPACING_DEFAULT
        Label:
            text: "Current width:"
            size_hint_y: None
            height: self.texture_size[1]
            font_size: FONT_SIZE_TEXT
            text_size: self.width, None
            halign: "left"
        Label:
            id: current_width_label
            text: ""
            size_hint_y: None
            height: self.texture_size[1]
            font_size: FONT_SIZE_TEXT
            text_size: self.width, None
            halign: "left"
        Label:
            text: "Current height:"
            size_hint_y: None
            height: self.texture_size[1]
            font_size: FONT_SIZE_TEXT
            text_size: self.width, None
            halign: "left"
        Label:
            id: current_height_label
            text: ""
            size_hint_y: None
            height: self.texture_size[1]
            font_size: FONT_SIZE_TEXT
            text_size: self.width, None
            halign: "left"
        Label:
            text: "Fix size:"
            font_size: FONT_SIZE_TEXT
            text_size: self.width, None
            halign: "left"
        SwitchWidget:
            id: fix_size_switch
            size_hint_y: None
            height: self.texture_size[1]
            active: False
        Label:
            text: "Fixed width:"
            font_size: FONT_SIZE_TEXT
            text_size: self.width, None
            halign: "left"
        PlainTextInput:
            id: fixed_width_input
            text: "640"
            multiline: False
            size_hint_y: None
            height: self.minimum_height
            font_size: FONT_SIZE_TEXT
            disabled: True
        Label:
            text: "Fixed height:"
            font_size: FONT_SIZE_TEXT
            text_size: self.width, None
            halign: "left"
        PlainTextInput:
            id: fixed_height_input
            text: "480"
            multiline: False
            size_hint_y: None
            height: self.minimum_height
            font_size: FONT_SIZE_TEXT
            disabled: True
    ErrorMessageLabel:
        text: root.error_message
