# Copyright 2026 MusicScience37 (Kenta Kabashima)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#:import FloatTextInput func_sketch._gui.float_text_input.FloatTextInput
#:import FONT_SIZE_HEADER1 func_sketch._gui.constants.FONT_SIZE_HEADER1
#:import FONT_SIZE_HEADER2 func_sketch._gui.constants.FONT_SIZE_HEADER2
#:import FONT_SIZE_TEXT func_sketch._gui.constants.FONT_SIZE_TEXT
#:import SPACING_DEFAULT func_sketch._gui.constants.SPACING_DEFAULT
#:import PADDING_NAVIGATION func_sketch._gui.constants.PADDING_NAVIGATION
#:import GRAPH_BACKGROUND_COLOR func_sketch._gui.constants.GRAPH_BACKGROUND_COLOR
#:import NORMAL_TEXT_COLOR func_sketch._gui.constants.NORMAL_TEXT_COLOR
#:import SPLITTER_COLOR func_sketch._gui.constants.SPLITTER_COLOR
#:import NAVIGATION_BACKGROUND_COLOR func_sketch._gui.constants.NAVIGATION_BACKGROUND_COLOR

#:include common.kv
#:include explicit_curve_config_widget.kv
#:import ExplicitCurveConfigWidget func_sketch._gui.explicit_curve_config_widget.ExplicitCurveConfigWidget
#:import PlainSplitterStrip func_sketch._gui.plain_splitter_strip.PlainSplitterStrip

<Splitter>:
    strip_cls: PlainSplitterStrip

<FuncSketchWidget>
    orientation: "horizontal"
    BoxLayout:
        canvas.before:
            Color:
                rgba: GRAPH_BACKGROUND_COLOR
            Rectangle:
                pos: self.pos
                size: self.size
        orientation: "vertical"
        Label:
            text: "Main Content"
    Splitter:
        canvas.before:
            Color:
                rgba: NAVIGATION_BACKGROUND_COLOR
            Rectangle:
                pos: self.pos
                size: self.size
        sizable_from: "left"
        size_hint_x: None
        width: 300
        minimum_width: 200
        max_width: 1000
        ScrollView:
            BoxLayout:
                orientation: "vertical"
                size_hint_y: None
                height: self.minimum_height
                spacing: SPACING_DEFAULT
                padding: PADDING_NAVIGATION
                BoxLayout:
                    orientation: "vertical"
                    size_hint_y: None
                    height: self.minimum_height
                    spacing: SPACING_DEFAULT
                    Label:
                        text: "Range"
                        size_hint_y: None
                        height: self.texture_size[1]
                        font_size: FONT_SIZE_HEADER1
                        halign: "left"
                    GridLayout:
                        cols: 3
                        size_hint_y: None
                        height: self.minimum_height
                        spacing: SPACING_DEFAULT
                        Label:
                            text: "x range:"
                            size_hint_x: None
                            width: self.texture_size[0]+5
                            font_size: FONT_SIZE_TEXT
                            halign: "left"
                        FloatTextInput:
                            multiline: False
                            size_hint_y: None
                            height: self.minimum_height
                            value: -3.0
                            font_size: FONT_SIZE_TEXT
                        FloatTextInput:
                            multiline: False
                            size_hint_y: None
                            height: self.minimum_height
                            value: 3.0
                            font_size: FONT_SIZE_TEXT
                        Label:
                            text: "y range:"
                            size_hint_x: None
                            width: self.texture_size[0]
                            font_size: FONT_SIZE_TEXT
                            halign: "left"
                        FloatTextInput:
                            multiline: False
                            size_hint_y: None
                            height: self.minimum_height
                            value: -3.0
                            font_size: FONT_SIZE_TEXT
                        FloatTextInput:
                            multiline: False
                            size_hint_y: None
                            height: self.minimum_height
                            value: 3.0
                            font_size: FONT_SIZE_TEXT
                BoxLayout:
                    orientation: "vertical"
                    size_hint_y: None
                    height: self.minimum_height
                    spacing: SPACING_DEFAULT
                    Label:
                        text: "Functions"
                        size_hint_y: None
                        height: self.texture_size[1]
                        font_size: FONT_SIZE_HEADER1
                        halign: "left"
                    ExplicitCurveConfigWidget:
                        curve_name: "Function 1"
                    ExplicitCurveConfigWidget:
                        curve_name: "Function 2"
                        error_message: "Test error message."
                    ExplicitCurveConfigWidget:
                        curve_name: "Function 3"
