#!/usr/bin/env python3

# This file is licensed under MIT license as follows:
#
# Copyright 2026 MusicScience37 (Kenta Kabashima)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""Helper script to create lists of source code for build."""

from pathlib import Path

THIS_DIR = Path(__file__).parent.absolute()

SOURCE_PATHS = [
    THIS_DIR.parent / "cpp" / "src" / "func_sketch",
    THIS_DIR.parent / "cpp" / "tests" / "units",
]

SOURCE_LIST_CMAKE_SUFFIX = "source_list.cmake"


def list_source_files(base_dir: Path) -> list[Path]:
    """List source files.

    Args:
        base_dir (Path): Base directory.

    Returns:
        list[Path]: Paths of source files.
    """
    files: list[Path] = []
    for child in base_dir.iterdir():
        if child.is_dir():
            files = files + list_source_files(child)
        elif child.is_file() and str(child.suffix) == ".cpp":
            files = files + [child]
    return files


def list_source_file_paths(base_path: Path) -> list[str]:
    """List source files in unit test.

    Args:
        base_path (Path): Base directory path.

    Returns:
        list[str]: Paths of source files.
    """
    source_files = list_source_files(base_path)
    return sorted(
        str(source_file.relative_to(base_path)).replace("\\", "/")
        for source_file in source_files
    )


def write_cmake_var_file(base_path: Path, file_paths: list[str]):
    """Write CMake script of source files.

    Args:
        base_path (Path): Base directory path.
        file_paths (list[str]): Paths of source files.
    """
    source_list_cmake_path = base_path / SOURCE_LIST_CMAKE_SUFFIX
    with open(
        str(source_list_cmake_path), mode="w", encoding="ascii", newline="\n"
    ) as file:
        file.write(
            "# This file is automatically generated by scripts/update_source_list.py\n"
        )
        file.write("set(SOURCE_FILES\n")
        for source_file in file_paths:
            file.write(f"    {source_file}\n")
        file.write(")\n")


def main():
    """Main function."""
    for base_path in SOURCE_PATHS:
        file_paths = list_source_file_paths(base_path)
        write_cmake_var_file(base_path, file_paths)


if __name__ == "__main__":
    main()
